# Generated by Django 5.0.1 on 2025-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('men', 'Men'), ('Woman', 'Woman')], max_length=100, unique=True),
        ),
    ]
