# Generated by Django 5.0.1 on 2025-09-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
