# Generated by Django 5.0.1 on 2025-12-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizestock',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=16),
        ),
    ]
